# Opacity (0.0 = fully transparent, 1.0 = solid)
active-opacity = 0.95;
inactive-opacity = 0.90;

# this is make it slightly dim for inactive windows
inactive-dim = 0.1;

# Opaticy Rule for i3lock

opacity-rule = [
  "100:class_g = 'i3lock'",
  "96:class_g = 'librewolf'",
  "100:class_g = 'org.vinegarhq.Sober'",
  "95:class_g = 'discord'"
];

# this enables fading
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;

# Vsync
vsync = true;

# Backend (better performance)
backend = "glx";
